class Constantes:
    SEGUNDOS_POR_PASO = 0.5
    
    MAX_CANTIDAD_PEATONES = 100

    VEHICULO_LARGO_CELDAS = 6
    VEHICULO_ANCHO_CELDAS = 5

    ARRIBOS_POR_SEGUNDO_AUTO = 1 / 6
    ARRIBO_POR_SEGUNDO_PEATON = 2

    ANCHO_VEREDA_METROS = 10
    ANCHO_PARTE_SUPERIOR_METROS = 8
    ANCHO_PARTE_INFERIOR_METROS = 8

    CALLE_LARGO_METROS = 21
    PASO_PEATONAL_ANCHO_METROS = 3
    CANTIDAD_DE_CARRILES = 6
    ANCHO_CARRIL_METROS = 3.5
    ANCHO_CELDA_METROS = 0.5
